### ISSUE TITLE
Create article on creating config files in R

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubAdmin#8] opened 2023-04-11 11:37 UTC
Dependant on resolving Infectious-Disease-Modeling-Hubs/hubAdmin#7 & https://github.com/ropensci/jsonvalidate/issues/65

**Comment by nickreich** [comment] 2024-06-03 14:50
Noting that this issue is a duplicate of [this one](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/issues/100). So I will close this one in favor of the other. @micokoch does the discussion on the other issue resolve any lingering questions?

**Closed by nickreich** 2024-06-03 14:50 UTC
Labels: documentation

**Comment by micokoch** [comment] 2024-06-03 14:56
I think the discussion on the other issue addresses most of my questions, and I'll take a stab at it on Wednesday.
